### ISSUE TITLE
Voting broken?

### ISSUE THREAD

**Issue by d3ddev3** [Factorio-Biter-Battles/Factorio-Biter-Battles#473] opened 2024-04-10 14:38 UTC
2 Players.
1 North (me)
1 South

I vote for ITYTD (very easy). South votes for Fun and Fast, so the difficulty is set to FNF. Shouldn't the system pick the median, and the assigned difficulty should be 'normal'?

**Comment by clifffrey** [comment] 2024-04-10 15:33
Right now, the system picks the median of things that were voted for, which is potentially a reasonable choice.  If you want to make a change to this, it'll need a combination of someone willing to make the change, and a vote in discord to make sure that the community wants the new behavior.

Without those, I am going to close this as intended behavior.

**Closed by clifffrey** 2024-04-10 15:33 UTC
